services:
  resumepro:
    image: ${DOCKERHUB_USERNAME}/resumepro:latest
    build:
      context: .
      dockerfile: demo/ResumePro/Dockerfile
    ports:
      - "3000:3000"

  identitypro:
    image: ${DOCKERHUB_USERNAME}/identitypro:latest
    build:
      context: .
      dockerfile: demo/IdentityPro/Dockerfile
    ports:
      - "3000:3000"

  resumeprotest:
    build:
      context: .
      dockerfile: demo/ResumePro/ResumePro.IntegrationTests/Dockerfile
