services:
  resumepro:
    image: ${DOCKERHUB_USERNAME}/resumepro:latest
    build:
      context: .
      dockerfile: ./demo/ResumePro/Dockerfile
    ports:
      - "5229:5229"

  identitypro:
    image: ${DOCKERHUB_USERNAME}/identitypro:latest
    build:
      context: .
      dockerfile: ./demo/IdentityPro/Dockerfile
    ports:
      - "5157:5157"