services:
  resumepro:
    image: ${DOCKERHUB_USERNAME}/resumepro:latest
    build:
      context: .
      dockerfile: ./demo/ResumePro/Dockerfile
    ports:
      - "3000:3000"

  identitypro:
    image: ${DOCKERHUB_USERNAME}/identitypro:latest
    build:
      context: .
      dockerfile: ./demo/IdentityPro/Dockerfile
    ports:
      - "3000:3000"
- 



version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: RESUMEPROUSER
      POSTGRES_PASSWORD: RESUMEPROPASSWORD
      POSTGRES_DB: RESUMEPRO
      PGDATABASE: RESUMEPRO
      PGUSER: RESUMEPROUSER
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U RESUMEPROUSER"]
      interval: 10s
      timeout: 5s
      retries: 5

  resumeprotest:
    build:
      context: .
      dockerfile: demo/ResumePro/ResumePro.IntegrationTests/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Pass connection string to your tests (adjust as needed)
      ConnectionStrings__PostgreSQLConnection: "Host=db;Port=5432;Username=RESUMEPROUSER;Password=RESUMEPROPASSWORD;Database=RESUMEPRO"
    # Run the tests automatically when the container starts
    command: ["dotnet", "test", "--no-build", "--logger:console"]

volumes:
  postgres_data:
