name: Build and Publish NuGet Packages

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Using .NET 8

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Pack NuGet Packages
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      - name: Publish NuGet Packages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          for package in ./nupkg/Bespoke.*.nupkg; do
            echo "Pushing $package"
            dotnet nuget push "$package" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          done

      # Docker steps
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -f demo/IdentityPro/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/identitypro.idp:latest .

      - name: Push Docker Image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/identitypro.idp:latest
